esphome:
  name: blinklicht-klingel
  friendly_name: blinklicht_klingel

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qik2FNjalQg+xTt8dWDcd6fzlfQFb8HbCnlwe3H39qA="

mqtt:
  broker: mqtt.int.vspace.one

ota:
  - platform: esphome
    password: "e0cfcd8d74160418ca12fc1e49f43c44"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Blinklicht-Klingel"
    password: "Tmz0UH2aH9a3"

captive_portal:

status_led:
  pin: 3

binary_sensor:
  - platform: gpio
    pin: GPIO11
    name: "Klingel betätigt"
    id: button
  - platform: status
    name: "Klingel online"
