dies_ist_eine_vorlage:

esphome:
  name: supermini-bt-proxy
  name_add_mac_suffix: true
  friendly_name: "ESP-C3-SuperMini BT-Proxy"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pJqOs93Tw5uNiEDJK6jWFBgRSnewj/PJNyffidbsdVE="

ota:
  - platform: esphome
    password: "d532150c94a712a1d77a3db4e0adc89f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-C3-Supermini-Bt-Proxy"
    password: "DKVDdOOhRXx7"

captive_portal:

status_led:
  pin: 8

improv_serial:

esp32_improv:
  authorizer: btn

bluetooth_proxy:
  active: True

esp32_ble_beacon:
  type: iBeacon
  uuid: '170841a7-826a-c250-30cf-bbd8c91a8eb5'
  major: 1337
  minor: 9999
  tx_power: 9dBm

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      inverted: True
      mode: 
        pullup: True
        input: True
    id: btn

  - platform: status
    name: "Online"
    id: online