esphome:
  name: esp_speaker
  on_boot: 
    then:
      - media_player.volume_set: 85%

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

# Enable logging
logger:
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: ""

ota:
  platform: esphome
  password: "speak"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true

  manual_ip: 
    static_ip: 10.0.8.24
    subnet: 255.255.252.0
    gateway: 10.0.8.1
    dns1: 10.0.8.1
    dns2: 1.1.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPhome Speaker"
    password: "Bz6wWFdn5ISY"

captive_portal:

i2s_audio:
  i2s_lrclk_pin: GPIO27
  i2s_bclk_pin: GPIO16


media_player:
  - platform: speaker
    id: mp
    announcement_pipeline:
      speaker: spk
      format: WAV
      sample_rate: 16000
      num_channels: 1
    #media_pipeline:
    #  speaker: spk_media
    #  format: WAV
    #  sample_rate: 32000
    #  num_channels: 1
    codec_support_enabled: false
    name: ESPHome Speaker
    buffer_size: 32000
    on_pause:
      button.press: device_restart
    #on_idle:
    #  button.press: device_restart
    on_announcement:
      - output.turn_off: mute
    on_play:
      - output.turn_off: mute

speaker:
  - platform: i2s_audio
    id: spk
    sample_rate: 16000
    dac_type: external
    use_apll: true
    channel: left
    i2s_dout_pin: GPIO25
    i2s_comm_fmt: stand_i2s
#    mute_pin:
#      number: 17
#      inverted: true

output:
  - platform: gpio
    id: mute
    pin:
      number: 17
      inverted: true
    

button:
  - platform: restart
    name: "ESP-Speaker Restart"
    id: device_restart

binary_sensor:
  - platform: gpio
    pin:
      number: 18
      inverted: true
      mode: INPUT_PULLUP
    name: "ESPHome Speaker Button"
    filters:
      - delayed_on: 10ms

  - platform: status
    name: "Online"
    id: online
