esphome:
  name: feinspahnmesser1
  friendly_name: feinspahnmesser1

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "65f694d9321b6163cfdd922829b40a15"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Feinspahnmesser1"
    password: "JPM2WrHCDlBm"

captive_portal:

status_led:
  pin: 2

uart:
  rx_pin: 4
  baud_rate: 9600

i2c:
  sda: 25
  scl: 27

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter <2.5µm"
  - platform: aht10
    temperature:
      name: "Feinspahnmesser 1 Temperatur"
    humidity:
      name: "Feinspahnmesser 1 Feuchte"
    