esphome:
  name: feinstaub2
  friendly_name: feinstaub2

esp32:
  board: esp32-s2-saola-1 # actually repurposed development prototype
  variant: esp32s2

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "VfX4uQdIFW79AyFQIJ12QYKF4N0wUgeE2d6kZE3wiCo="

ota:
  platform: esphome
  password: "c439a3074d497c8b47dcbe0211fed7cb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Feinstaub2 Fallback Hotspot"
    password: "f0BBwWJFaID1"

captive_portal:

status_led:
  pin: 3

uart:
  - rx_pin: 43
    baud_rate: 9600
    id: pm25uart
  - rx_pin: 7
    tx_pin: 6
    baud_rate: 9600
    id: co2uart

sensor:
  - platform: mhz19
    uart_id: co2uart
    co2:
      name: "MH-Z19 CO2 Value"
#    temperature:
#      name: "MH-Z19 Temperature"
  - platform: pm1006
    uart_id: pm25uart
    pm_2_5:
      id: 
      name: "Feinstaub"
  - platform: dht
    pin: 5
    model: DHT22
    temperature:
      name: "Temperatur"
    humidity:
      name: "Feuchte"
