esphome:
  name: feinspahnmesser1
  friendly_name: feinspahnmesser1

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

mqtt:
  broker: mqtt.int.vspace.one

ota:
  platform: esphome
  password: "65f694d9321b6163cfdd922829b40a15"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Feinspahnmesser1"
    password: "JPM2WrHCDlBm"

captive_portal:

status_led:
  pin: 2

uart:
  - rx_pin: 4
    baud_rate: 9600
    id: pm25uart
  - rx_pin: GPIO17
    tx_pin: GPIO21
    baud_rate: 9600
    id: co2uart

i2c:
  sda: 25
  scl: 27


sensor:
  - platform: mhz19
    uart_id: co2uart
    co2:
      name: "MH-Z19 CO2 Value"
#    temperature:
#      name: "MH-Z19 Temperature"
    update_interval: 60s
  - platform: pm1006
    uart_id: pm25uart
    pm_2_5:
      name: "Particulate Matter <2.5µm"
  - platform: aht10
    temperature:
      name: "Feinspahnmesser 1 Temperatur"
    humidity:
      name: "Feinspahnmesser 1 Feuchte"
    