esphome:
  name: lichtstreifen-perfboard-1
  friendly_name: lichtstreifen_perfboard_1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fZzIQl14FaubX3G8+hd2m0hcd9ZxkxR0uW9ri9xySRY="

ota:
  platform: esphome
  password: "c495198a086e0fa20c36f627857a0b0c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lichtstreifen-Perfboard-1"
    password: "r7pARFN42fyB"

captive_portal:

light:
  - platform: rgb
    name: "Lichtstreifen Wabbel"
    red: r
    green: g
    blue: b
    id: strip
    effects:
      - lambda:
          name: Slow Rainbow
          update_interval: 1s
          lambda: |-
            const float cycle_time = 12;
            auto call = id(strip).turn_on();
            call.set_publish(false);
            call.set_save(false);
            call.set_transition_length(1000);
            float t = fmod((3 * millis())/(cycle_time * 1000), 3);
            float i = fmod(t,1);
            if (0 <= t && t <= 1) call.set_rgb(i, 0, 1-i);
            else if (1 <= t && t <= 2) call.set_rgb(1-i, i, 0);
            else if (2 <= t && t <= 3) call.set_rgb(0, 1-i, i);
            call.perform();

output:
  - platform: esp8266_pwm
    id: g
    frequency: 5000Hz
    pin:
      number: 0
      inverted: True
  - platform: esp8266_pwm
    id: r
    frequency: 5000Hz
    pin:
      number: 2
      inverted: True
  - platform: esp8266_pwm
    id: b
    frequency: 5000Hz
    pin:
      number: RX
      inverted: False