esphome:
  name: lichtstreifen-perfboard-1
  friendly_name: lichtstreifen_perfboard_1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fZzIQl14FaubX3G8+hd2m0hcd9ZxkxR0uW9ri9xySRY="

ota:
  password: "c495198a086e0fa20c36f627857a0b0c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lichtstreifen-Perfboard-1"
    password: "r7pARFN42fyB"

captive_portal:

light:
  - platform: rgb
    name: "Lichtstreifen Wabbel"
    red: r
    green: g
    blue: b

output:
  - platform: esp8266_pwm
    id: g
    frequency: 5000Hz
    pin:
      number: 0
      inverted: True
  - platform: esp8266_pwm
    id: r
    frequency: 5000Hz
    pin:
      number: 2
      inverted: True
  - platform: esp8266_pwm
    id: b
    frequency: 5000Hz
    pin:
      number: RX
      inverted: False