esphome:
  name: luftsensor3
  friendly_name: luftsensor3

esp32:
  board: esp32-s2-saola-1 # actually repurposed development prototype
  variant: esp32s2

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "VfX4uQdIFW79AyFQIJ12QYKF4N0wUgeE2d6kZE3wiCo="

mqtt:
  broker: mqtt.int.vspace.one

ota:
  platform: esphome
  password: "c439a3074d497c8b47dcbe0211fed7cb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip: 
    static_ip: 10.0.8.16
    subnet: 255.255.252.0
    gateway: 10.0.8.1
    dns1: 10.0.8.1
    dns2: 1.1.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "luftsensor3 Fallback Hotspot"
    password: "f0BBwWJFaID1"

captive_portal:

status_led:
  pin:
    number: 3
    inverted: true

uart:
  - rx_pin: 5
    tx_pin: 7
    baud_rate: 9600
    id: co2uart

i2c:
  scl: 43
  sda: 9

sensor:
  - platform: mhz19
    uart_id: co2uart
    co2:
      name: "CO2"
      id: actual_co2
  - platform: ccs811
    tvoc:
      name: "TVOC"
      id: tvoc
    eco2:
      id: estimated_co2
    address: 0x5A
  - platform: aht10
    temperature:
      name: "Temperatur"
    humidity:
      name: "Feuchte"
  - platform: hdc1080
    temperature:
      name: "Temperatur Shitty"
      id: temp
    humidity:
      name: "Feuchte Shitty"
      id: hum

binary_sensor:
  - platform: status
    name: "Online"
    id: online