esphome:
  name: magichome-dingens-ohne-w
  friendly_name: magichome_dingens_ohne_w

esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "cv6gt3U3ua0jRCOkJlmwJhxBgDkIbmvz/ahWVIeHCmY="

ota:
  password: "63fa32a6729a47c8b7ad2d9f171e4efa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Magichome-Dingens-Ohne-W"
    password: "NUM7OUSudJau"

captive_portal:

light:
  - platform: rgb
    name: "MH RGB Streifen"
    red: r
    green: g
    blue: b

output:
  - platform: esp8266_pwm
    id: r
    frequency: 3000Hz
    pin:
      inverted: false
      number: 5
  - platform: esp8266_pwm
    id: g
    frequency: 3000Hz
    pin:
      inverted: false
      number: 12
  - platform: esp8266_pwm
    id: b
    frequency: 3000Hz
    pin:
      inverted: false
      number: 13
#  - platform: esp8266_pwm
#    id: w
#    frequency: 3000Hz
#    pin:
#      inverted: false
#      number: 15

#remote_receiver:
#  pin: 4