esphome:
  name: magichome-dinger
  friendly_name: magichome_dinger

esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "UmmUfzmOY5uWAW5ZDLQ+7Yc+Lg52cjdJwSbxxz4H5Xw="

mqtt:
  broker: mqtt.int.vspace.one

ota:
  platform: esphome
  password: "304e111ea5982a2240c1b715ba6cea7b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip: 
    static_ip: 10.0.8.20
    subnet: 255.255.252.0
    gateway: 10.0.8.1
    dns1: 10.0.8.1
    dns2: 1.1.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Magichome-Dinger"
    password: "eYyZ1BzICLzm"

captive_portal:

web_server:
  ota: False
  local: True

light:
  - platform: rgbw
    name: "MH RGBW Streifen"
    red: r
    green: g
    blue: b
    white: w
    id: strip
    effects:
      - lambda:
          name: Slow Rainbow
          update_interval: 1s
          lambda: |-
            const float cycle_time = 12;
            auto call = id(strip).turn_on();
            call.set_publish(false);
            call.set_save(false);
            call.set_transition_length(1000);
            float t = fmod((3 * millis())/(cycle_time * 1000), 3);
            float i = fmod(t,1);
            if (0 <= t && t <= 1) call.set_rgb(i, 0, 1-i);
            else if (1 <= t && t <= 2) call.set_rgb(1-i, i, 0);
            else if (2 <= t && t <= 3) call.set_rgb(0, 1-i, i);
            call.perform();

output:
  - platform: esp8266_pwm
    id: r
    frequency: 3000Hz
    pin:
      inverted: false
      number: 5
  - platform: esp8266_pwm
    id: g
    frequency: 3000Hz
    pin:
      inverted: false
      number: 12
  - platform: esp8266_pwm
    id: b
    frequency: 3000Hz
    pin:
      inverted: false
      number: 13
  - platform: esp8266_pwm
    id: w
    frequency: 3000Hz
    pin:
      inverted: false
      number: 15

#remote_receiver:
#  pin: 4

binary_sensor:
  - platform: status
    name: "Online"
    id: online