#Controller for two buttons in the vspace.one central control-box
#Buttons can be pressed tempoarily and can output 1bit RGB colors

substitutions:
  entity_id_space_state: switch.space_state
  entity_id_rundumlicht: switch.blinklicht_klingel_rundumlicht

esphome:
  name: steuerbox
  friendly_name: "Steuerbox"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  homeassistant_services: True
  encryption:
    key: "swDbwNjheWgw62851e4iOvNVaPVWVC8re78cTuBmQiU="

#mqtt:
#  broker: mqtt.int.vspace.one

ota:
  - platform: esphome
    password: "2854835fd37f3038507488080261d22c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip: 
    static_ip: 10.0.8.29
    subnet: 255.255.252.0
    gateway: 10.0.8.1
    dns1: 10.0.8.1
    dns2: 1.1.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Steuerbox Fallback Hotspot"
    password: "7pMF0Sb2jEaE"

captive_portal:

status_led:
  pin: 2

switch:
  - platform: homeassistant
    id: ha_space_state_switch
    entity_id: ${entity_id_space_state}
    restore_mode: DISABLED
  - platform: homeassistant
    id: ha_rundumlicht_switch
    entity_id: ${entity_id_rundumlicht}
    restore_mode: DISABLED

text_sensor:
  - platform: homeassistant
    id: ha_space_state
    entity_id: ${entity_id_space_state}
    on_value: 
      then:
        - if:
            condition:
              lambda: 'return x == "on";'
            then:
              - light.turn_on:
                  id: space_state_led
                  brightness: 100%
                  red: 0%
                  green: 100%
                  blue: 0%
                  effect: none
            else:
              - if:
                  condition:
                    lambda: 'return x == "off";'
                  then:
                    - light.turn_on:
                        id: space_state_led
                        brightness: 100%
                        red: 100%
                        green: 0%
                        blue: 0%
                        effect: none
                  else:
                    - light.turn_on:
                        id: space_state_led
                        brightness: 100%
                        red: 100%
                        green: 65%
                        blue: 0%
                        effect: none

  - platform: homeassistant
    id: ha_rundumlicht_state
    entity_id: ${entity_id_rundumlicht}
    on_value: 
      then:
        - if:
            condition:
              lambda: 'return x == "on";'
            then:
              - light.turn_on:
                  id: rundumlicht_led
                  brightness: 100%
                  red: 0%
                  green: 100%
                  blue: 0%
                  effect: none
            else:
              - if:
                  condition:
                    lambda: 'return x == "off";'
                  then:
                    - light.turn_on:
                        id: rundumlicht_led
                        brightness: 100%
                        red: 100%
                        green: 0%
                        blue: 0%
                        effect: none
                  else:
                    - light.turn_on:
                        id: rundumlicht_led
                        brightness: 100%
                        red: 100%
                        green: 65%
                        blue: 0%
                        effect: none

binary_sensor:
  - platform: status
    id: is_online
    name: "Steuerbox Online"
  - platform: gpio
    id: space_state_btn
    name: "Steuerbox Space-State Toggle Button"
    disabled_by_default: False
    pin:
      number: GPIO14
      inverted: True
      mode:
        input: True
        pullup: True
    #filters:
    #  - delayed_on: 100ms
    #  - delayed_off: 100ms
    on_press:
      - homeassistant.action:
          action: switch.toggle
          data:
            entity_id: switch.space_state
  - platform: gpio
    id: rundumlicht_btn
    name: "Steuerbox Rundumlicht Toggle Button"
    disabled_by_default: False
    pin:
      number: GPIO12
      inverted: True
      mode:
        input: True
        pullup: True
    #filters:
    #  - delayed_on: 100ms
    #  - delayed_off: 100ms
    on_press:
      - homeassistant.action:
          action: switch.toggle
          data:
            entity_id: switch.blinklicht_klingel_rundumlicht


light:
  - platform: neopixelbus
    id: button_leds
    type: RGB
    variant: WS2811
    pin: GPIO5
    num_leds: 2
  - platform: partition
    id: space_state_led
    disabled_by_default: True
    entity_category: DIAGNOSTIC
    name: "Steuerbox Space-State LED"
    icon: "mdi:led-off"
    segments:
    - id: button_leds
      from: 0
      to: 0
    effects:
      - pulse:
          name: "blink"
          transition_length: 0.1s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
  - platform: partition
    id: rundumlicht_led
    disabled_by_default: True
    entity_category: DIAGNOSTIC
    name: "Steuerbox Rundumlicht LED"
    icon: "mdi:led-off"
    segments:
    - id: button_leds
      from: 1
      to: 1
    effects:
      - pulse:
          name: "blink"
          transition_length: 0.1s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
