#Controller for two buttons in the vspace.one central control-box
#Buttons can be pressed tempoarily and can output 1bit RGB colors

esphome:
  name: steuerbox
  friendly_name: "Steuerbox"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "swDbwNjheWgw62851e4iOvNVaPVWVC8re78cTuBmQiU="

mqtt:
  broker: mqtt.int.vspace.one

ota:
  - platform: esphome
    password: "2854835fd37f3038507488080261d22c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Steuerbox Fallback Hotspot"
    password: "7pMF0Sb2jEaE"

captive_portal:

status_led:
  pin: 2


http_request:
  verify_ssl: false
script:
  - id: rundumlicht_toggle_script
    then:
      - http_request.post:
          url: "http://10.0.8.12/switch/rundumlicht/toggle"
          capture_response: True
          on_response:
            then:
              lambda: |-
                auto call = id(rundumlicht_led).turn_on();
                call.set_transition_length(100);
                call.set_rgb(1.0,0.8,0.0); //default error color
                if (response->status_code == 200) json::parse_json(body, [](JsonObject root) -> bool {
                  if (root["value"]) {
                    if (root["value"]) call.set_rgb(1.0,0.0,0.5);;
                    else call.set_rgb(1.0,0.0,0.5);
                    return true;
                  }
                  else {
                    ESP_LOGI(TAG,"No 'value' key in this json!");
                    return false;
                  }
                });
                call.perform();
          on_error:
            then:
              light.turn_on:
                id: rundumlicht_led
                red: 100%
                green: 75%
                blue: 0%
                effect: "blink"


binary_sensor:
  - platform: status
    id: is_online
    name: "Steuerbox Online"
  - platform: gpio
    id: space_state_btn
    name: "Steuerbox Space-State Toggle Button"
    pin:
      number: GPIO4
      inverted: True
      mode:
        input: True
        pullup: True
    filters:
      - settle: 100ms
  - platform: gpio
    id: rundumlicht_btn
    name: "Steuerbox Rundumlicht Toggle Button"
    disabled_by_default: True
    entity_category: DIAGNOSTIC
    pin:
      number: GPIO5
      inverted: True
      mode:
        input: True
        pullup: True
    filters:
      - settle: 100ms

light:
  - platform: neopixelbus
    id: button_leds
    type: GRB
    variant: WS2811
    pin: GPIO12
    num_leds: 2
  - platform: partition
    id: space_state_led
    disabled_by_default: False
    entity_category: CONFIG
    name: "Steuerbox Space-State LED"
    icon: "mdi:led-off"
    segments:
    - id: button_leds
      from: 0
      to: 0
  - platform: partition
    id: rundumlicht_led
    disabled_by_default: True
    entity_category: DIAGNOSTIC
    name: "Steuerbox Rundumlicht LED"
    icon: "mdi:led-off"
    segments:
    - id: button_leds
      from: 1
      to: 1