esphome:
  name: vspace-logo
  friendly_name: vspace_logo
  includes:
    - light_effects.h
  on_boot:
    then:
      - light.turn_on:
          id: inner_strip
          brightness: 100%
          red: 10%
          green: 100%
          blue: 50%
      - light.turn_on:
          id: rim_strip
          brightness: 100%
          red: 100%
          green: 20%
          blue: 80%

esp8266:
  board: huzzah

# Enable logging
logger:
  hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: "+p5LV+KTeHkISiXVReysu3dYTBbS6aqCDojCiEeDdXk="

ota:
  password: "8fd5374e68bff81e309da69b0b102ebf"

#status_led:
#  pin: GPIO2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vspace-Logo Fallback Hotspot"
    password: "Gp4sfpJWpOfU"

captive_portal:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO3
    num_leds: 63
    id: rim_strip
    name: "vspace_logo rim"
    method:
      type: esp8266_dma
    effects:
      - addressable_rainbow:
          name: "Rainbow"
          speed: 10
          width: 63
      - addressable_lambda:
          name: "Pride"
          lambda: "pride_circle(it, pride_flag,6);"
      - addressable_lambda:
          name: "Traaa"
          lambda: "pride_circle(it, trans_flag,5);"
      - addressable_lambda:
          name: "Sine"
          update_interval: 5ms
          lambda: |-
            double m = millis()/10;
            for (int i = 0; i < it.size(); i++) {
              it[i] = current_color * ((sin((float(i*(360/it.size()))+m)*PI/180) + 1) * 127);
            }
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO1
    num_leds: 60
    id: inner_strip
    name: "vspace_logo inner"
    method:
      type: esp8266_uart
      bus: 0
      async: true
    effects:
      - addressable_rainbow:
          name: "Rainbow"
          speed: 10
          width: 60
      - addressable_lambda:
          name: "Pride"
          lambda: "pride_circle(it, pride_flag,6);"
      - addressable_lambda:
          name: "Traaa"
          lambda: "pride_circle(it, trans_flag,5);"
      - addressable_lambda:
          name: "Sine"
          update_interval: 5ms
          lambda: |-
            double m = millis()/10;
            for (int i = 0; i < it.size(); i++) {
              it[i] = current_color * ((sin((float(i*(360/it.size()))+m)*PI/180) + 1) * 127);
            }
